language: python
python:
    - 3.6
    - 3.7
    - 3.8
env:
  global:
    LO_VERSION=5.1.1.3
    LO_PATH=/opt/libreoffice5.1/program

install: pip install -U tox-travis

# Setup Libre Office
before_install:
  - sudo bash ci/linux.sh
sudo: required
script: tox --recreate && tox
